apiVersion: v1
kind: Pod
metadata:
  name: test1
  namespace: validation
  labels:
    billing: customer1
    unit: dev103
  annotations:
    # invalid annotation
    #"k8s.questionable.services/id":  "abc"
    # valid annotation
    "k8s.questionable.services/hostname": "abc.example.com"
spec:
  restartPolicy: OnFailure
  containers:
    - name: test1
      image: nginx
      resources:
        requests:
          cpu: 25m
          memory: 263M
        limits:
          cpu: 25m
          memory: 263M      
      imagePullPolicy: Always