apiVersion: v1
kind: Pod
metadata:
  name: test1
  labels:
    billing: customer1
    unit: dev103
spec:
  restartPolicy: OnFailure
  containers:
    - name: test1
      image: nginx
      resources:
        requests:
          cpu: 25m
          memory: 263M
        limits:
          cpu: 25m
          memory: 263M      
      imagePullPolicy: Always