apiVersion: v1
kind: Pod
metadata:
  name: test2
  #namespace: validation
  namespace: enforce-annotations
spec:
  restartPolicy: OnFailure
  containers:
    - name: spam
      image: nginx
      resources:
        requests:
          cpu: 25m
          memory: 263M
        limits:
          cpu: 25m
          memory: 263M      
      imagePullPolicy: Always