apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-webhook
  namespace: validation
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: mifomm/adserv2:latest
        command: ["/server"]
        #env:
        #  - name: HOSTNAME
        #    value: "admission-c0ntrol-example.questionable.services"
        #args:
        #  [
        #    "-host",
        #    "$(HOSTNAME)",
        #  ]          
        resources:
          requests:
            cpu: 25m
            memory: 263M
          limits:
            cpu: 25m
            memory: 263M        
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: webhook-api