apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-control
  namespace: validation
  labels:
    app: admission-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-control
  template:
    metadata:
      labels:
        app: admission-control
    spec:
      containers:
      - name: admission-control-example
        image: mifomm/webhook:latest
        resources:
          requests:
            cpu: 25m
            memory: 263M
          limits:
            cpu: 25m
            memory: 263M        
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: webhook-api